version: "3.8"
services:

  master:
    container_name: pg_master
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5431:5432
    volumes:
      - ./pg_master:/var/lib/postgresql/dat
    command: [ "postgres", "-c", "wal_level=logical" ]

  replica:
    container_name: pg_replica
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5432:5432
    volumes:
      - ./pg_replica:/var/lib/postgresql/dat