version: "3.8"
services:

  master:
    container_name: pg_master
    hostname: pg-master
    image: postgres
    environment:
      POSTGRES_DB: "pg_master"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5431:5432
    volumes:
      - ./pg_master:/var/lib/postgresql/dat
    command: [ "postgres", "-c", "wal_level=logical" ]

  replica:
    container_name: pg_replica
    hostname: pg-replica
    image: postgres
    environment:
      POSTGRES_DB: "pg_replica"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - ./pg_replica:/var/lib/postgresql/dat