version: "3.8"
services:

  pg_master:
    container_name: pg_master
    hostname: pg-master
    image: postgres
    environment:
      POSTGRES_DB: "master_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5433:5432
    volumes:
      - ./pg_master:/var/lib/postgresql/dat
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  pg_replica:
    container_name: pg_replica
    hostname: pg-replica
    image: postgres
    environment:
      POSTGRES_DB: "replica_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5434:5432
    volumes:
      - ./pg_replica:/var/lib/postgresql/dat
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql