FROM python

ENV PYTHONUNBUFFERED=1 \
	PYTHONDONTWRITEBYTECODE=1 \
	FROM_DOCKER_IMAGE=True

COPY . .
RUN pip install -r requirements.txt

ENTRYPOINT ["python", "./root/manage.py", "runserver", "0.0.0.0:8000"]